In [11]:
%matplotlib inline
import numpy as np
import pandas as pd



In [13]:
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

die1


array([4, 4, 6, ..., 1, 6, 2])

In [14]:
die2

array([1, 6, 5, ..., 4, 5, 3])

In [15]:
dies_equal = die1 == die2

In [16]:
dies_equal

array([False, False, False, ..., False, False, False])

In [24]:
number_of_equal = len(dies_equal[dies_equal == True])

In [22]:
total_number = len(dies_equal)
total_number

10000

In [26]:
probability = number_of_equal/total_number
probability

0.162

In [28]:
dies_equal.mean()

0.162

In [54]:
n_trials = nrows = 10_000
n_coins = ncols = 8
outcomes = [int(1), int(0)]
coin = np.random.choice(outcomes, size = (n_trials, n_coins))
coin_df = pd.DataFrame(coin)
coin_df

0  1  2  3  4  5  6  7
0     0  0  0  0  0  1  0  1
1     1  0  0  1  1  1  1  1
2     1  1  1  0  1  1  1  0
3     1  1  1  1  1  1  1  1
4     0  0  0  1  0  1  0  1
...  .. .. .. .. .. .. .. ..
9995  0  1  0  0  1  1  0  1
9996  1  0  1  1  1  0  1  1
9997  1  1  1  0  0  1  1  0
9998  0  1  1  1  0  1  0  1
9999  1  0  0  1  1  1  1  1

[10000 rows x 8 columns]

In [62]:
coin_df["sum"] = coin_df.sum(axis=1)
coin_df

0  1  2  3  4  5  6  7  sum
0     0  0  0  0  0  1  0  1    5
1     1  0  0  1  1  1  1  1    9
2     1  1  1  0  1  1  1  0    9
3     1  1  1  1  1  1  1  1   11
4     0  0  0  1  0  1  0  1    6
...  .. .. .. .. .. .. .. ..  ...
9995  0  1  0  0  1  1  0  1    7
9996  1  0  1  1  1  0  1  1    9
9997  1  1  1  0  0  1  1  0    8
9998  0  1  1  1  0  1  0  1    8
9999  1  0  0  1  1  1  1  1    9

[10000 rows x 9 columns]

In [68]:
is_three = coin_df["sum"] == 3
is_three
is_three = len(is_three[is_three == True])
coin_df_len = len(coin_df)

In [66]:
is_three.mean()

0.0042

In [69]:
is_three/coin_df_len

0.0042